version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - v1.x
image: Visual Studio 2017
install:
- ps: >-
    # Download .NET Core 2.0 Preview 2 SDK and add to PATH

    $urlCurrent = "https://download.microsoft.com/download/F/A/A/FAAE9280-F410-458E-8819-279C5A68EDCF/dotnet-sdk-2.0.0-preview2-006497-win-x64.zip"

    $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

    $env:DOTNET_CLI_TELEMETRY_OPTOUT = "true"

    $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"

    mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null

    $tempFileCurrent = [System.IO.Path]::GetTempFileName()

    (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)

    Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)

    $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

    $env:CommitHash = "$env:APPVEYOR_REPO_COMMIT"
cache: '%USERPROFILE%\.nuget\packages'
build_script:
- ps: >
    dotnet --version

    dotnet build -v q
    
    $cmd = "pack", "src\EventGridExtension\EventGridExtension.csproj", "-o", "..\..\buildoutput", "--no-build"
    
    if (![boolean]::Parse($env:APPVEYOR_REPO_TAG)) {
        Write-Host "No git tag found. Setting package suffix to '$env:APPVEYOR_BUILD_NUMBER'"
        $cmd += "--version-suffix", "-$env:APPVEYOR_BUILD_NUMBER"
    }
    
    dotnet $cmd
test_script:
- ps: >-
    dotnet test .\test\Extension.tests\ -v q --no-build
artifacts:
- path: buildoutput\*.nupkg
  name: Binaries
hosts:
  api.nuget.org: 93.184.221.200
