pool:
  name: Hosted VS2017
  demands: vstest

#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘VersionSuffix’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘VersionSuffix’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'
    arguments: '-c $(BuildConfiguration) -p:CommitHash=$(Build.SourceVersion);VersionSuffix=$(VersionSuffix)'

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning: Authenticode'
  inputs:
    ConnectedServiceName: 'ESRP Service'
    FolderPath: 'src/Extensions/bin/$(BuildConfiguration)/'
    Pattern: Microsoft.Azure.WebJobs.Extensions.EventGrid.dll
    signConfigType: inlineSignParams
    inlineOperation: |
     [    
         {
           "KeyCode": "CP-230012",
           "OperationCode": "SigntoolSign",
           "Parameters": {
             "OpusName": "Microsoft",
             "OpusInfo": "http://www.microsoft.com",
             "FileDigest": "/fd \"SHA256\"",
             "PageHash": "/NPH",
             "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
           },
           "ToolName": "sign",
           "ToolVersion": "1.0"
         },
         {
           "KeyCode": "CP-230012",
           "OperationCode": "SigntoolVerify",
           "Parameters": {},
           "ToolName": "sign",
           "ToolVersion": "1.0"
         }
     ]
  condition: and(succeeded(), startsWith(variables['SignArtifacts'], 'true'))

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: 'src/**/*.csproj'
    packDirectory: '$(Build.BinariesDirectory)'
    nobuild: true
    buildProperties: 'VersionSuffix=$(VersionSuffix)'
    verbosityPack: Normal

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning: Nupkg'
  inputs:
    ConnectedServiceName: 'ESRP Service'
    FolderPath: '$(Build.BinariesDirectory)'
    Pattern: '*.nupkg'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
         {
           "KeyCode": "CP-401405",
           "OperationCode": "NuGetSign",
           "Parameters": {},
           "ToolName": "sign",
           "ToolVersion": "1.0"
         },
         {
           "KeyCode": "CP-401405",
           "OperationCode": "NuGetVerify",
           "Parameters": {},
           "ToolName": "sign",
           "ToolVersion": "1.0"
         }
     ]
  condition: and(succeeded(), startsWith(variables['SignArtifacts'], 'true'))

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    searchFolder: '$(System.DefaultWorkingDirectory)\test'
    diagnosticsEnabled: True

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
